# version: '3'
# services:
#   apphost:
#     image: stevebrownlee/hubspotapps:latest
#     ports:
#       - "80:80"
#     deploy:
#       restart_policy:
#         condition: any
#         delay: 5s
#         max_attempts: 3
#         window: 120s

